### ISSUE TITLE
chunkstream.js: Uncaught TypeError: util.inherits is not a function

### ISSUE THREAD

**Issue by Amigs** [lukeapage/pngjs#290]
node_modules/pngjs/lib/chunkstream.js

**Comment by lukeapage** [comment]
Sorry no idea what this is about..

**Comment by jamaluddinrumi** [comment]
i'm just experience this too after using `@unpic/placeholder`

https://github.com/ascorbic/get-pixels/issues/4

**Comment by hawc** [comment]
Experienced this as well when using pngjs client side with Vite/Sveltekit. Probably caused by Vite not polyfilling Node.js builtins (like `util`). Should work fine after adding `vite-plugin-node-polyfills`.

**Comment by gustavopch** [comment]
I'm getting this error after upgrading Vite from v5 to v6. My web app uses Jimp which depends on this library.
<img width="601" alt="image" src="https://github.com/user-attachments/assets/3963fb77-49a7-421d-88d2-916a5677b7c2" />
See: https://vite.dev/guide/troubleshooting.html#module-externalized-for-browser-compatibility
